name: build-windows-msys2
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: gcc cmake ninja

      - name: build-and-test
        shell: msys2 {0}
        run: |
          cmake --preset ninjam-msys2
          cmake --build --preset ninjam-msys2 --config Release
          ctest --preset  --preset -C Release
