name: build-linux
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Fix robin-map CMake config
        run: cd /home/runner/work/omnichroma/omnichroma/vcpkg; echo 'configure_file("${CURRENT_PACKAGES_DIR}/share/${PORT}/tsl-robin-mapConfig.cmake" "${CURRENT_PACKAGES_DIR}/share/${PORT}/robin-mapConfig.cmake" COPYONLY)' >> ports/robin-map/portfile.cmake

      - uses: lukka/get-cmake@latest

      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v10

      - name: Run CMake consuming CMakePreset.json and vcpkg.json by mean of vcpkg.
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninjam-linux'
          buildPreset: 'ninjam-linux'
          buildPresetCmdString: "[`--build`, `--preset`, `$[env.BUILD_PRESET_NAME]`, `--config`, `Release`]"
          testPreset: 'ninjam-linux'
          testPresetCmdString: "[`--preset`, `$[env.TEST_PRESET_NAME]`, `-C`, `Release`]"

      - name: Run benchmarks
        run: ./build/ninjam-linux/bench/sets/Release/bench_sets